//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerConsole.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class atencion_medicos_dbEntities : DbContext
    {
        public atencion_medicos_dbEntities()
            : base("name=atencion_medicos_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aseguradora> aseguradora { get; set; }
        public virtual DbSet<atencion_medicos> atencion_medicos { get; set; }
        public virtual DbSet<estatus> estatus { get; set; }
        public virtual DbSet<medico> medico { get; set; }
        public virtual DbSet<responsabilidad> responsabilidad { get; set; }
    }
}
