//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerConsole.Hubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class atencion_medicos
    {
        public int id_atencion_medicos { get; set; }
        public Nullable<int> responsabilidad { get; set; }
        public Nullable<int> estatus { get; set; }
        public Nullable<System.DateTime> ingreso { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<System.DateTime> fecha_entrega_tab { get; set; }
        public Nullable<System.DateTime> fecha_solicitado { get; set; }
        public Nullable<System.DateTime> fecha_entregado { get; set; }
        public string siniestro { get; set; }
        public string paciente { get; set; }
        public string cuenta { get; set; }
        public Nullable<int> comp_aseguradora { get; set; }
        public Nullable<int> medico { get; set; }
        public string concepto_honorario { get; set; }
        public Nullable<double> importe { get; set; }
        public double isr { get; set; }
        public Nullable<double> renta_importe_cedular { get; set; }
        public double total { get; set; }
        public string factura { get; set; }
        public Nullable<int> cancelado_recibo { get; set; }
        public string recibe { get; set; }
        public Nullable<System.DateTime> fecha_enviado { get; set; }
        public Nullable<System.DateTime> fecha_reenviado { get; set; }
        public string folio_portal { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public string observaciones { get; set; }
        public string asistente { get; set; }
        public string correo { get; set; }
    
        public virtual aseguradora aseguradora { get; set; }
        public virtual estatus estatus1 { get; set; }
        public virtual medico medico1 { get; set; }
        public virtual responsabilidad responsabilidad1 { get; set; }
    }
}
